name: cert-2-aws-creds
author: Yenlin Chen (hencrice@)
description: >-
  Retrieve temporary AWS credentials using X.509 certificate.
  Inspired by https://docs.aws.amazon.com/iot/latest/developerguide/authorizing-direct-aws.html.

inputs: # inputs to this Action
  certificate:
    description: >-
      The the X.509 certificate (i.e. content of the file)
      that will be used when making the call to AWS to retrieve
      temporary credentials
    required: true
  private_key:
    description: >-
      The private key (i.e. content of the file) generated
      from the AWS IoT console. This key will be used when 
      making the call to AWS to retrieve temporary credentials
    required: true
  aws_role_arn:
    description: >-
      The ARN of the AWS IAM role that should be assumed by
      this GitHub Action. This should be one of the outputs
      after the action infrastructure Cloudformation stack
      is deployed
    required: true
  aws_region:
    description: >-
      The target AWS region this action will send requests to
    required: false
    default: us-west-2

outputs: # output will be consumable in later steps in the Github Action workflow
  aws_access_key_id:
    description: >-
      Temporary access key. Can be used to authN/authZ requests
      to AWS
  aws_secret_access_key:
    description: >-
      Temporary secret access key. Can be used to authN/authZ
      requests to AWS
  aws_session_token:
    description: >-
      STS session token. Required to be used along with
      the other temporary cerdentials in this output
  aws_region:
    description: >-
      The same aws region that was passed into this
      action as input. Can be referenced by future steps
      in the workflow so that region is hardcoded only once 
      in the input section of this action

runs:
  using: node12
  main: dist/index.js
